name: Format Code and Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Format code with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive game.py gameunittest.py  # Format the game.py and gameunittest.py files

    - name: Run linting with flake8
      run: |
        flake8 .  # Lint all Python files in the repo

    - name: Run unit tests with pytest
      run: |
        pytest gameunittest.py --maxfail=1 --disable-warnings -q  # Run tests in gameunittest.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m 'Auto-formatted code with autopep8' || echo "No changes to commit"
        git push  # Push changes back to the repository if any were made
