name: Python CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run linting with flake8
      run: |
        flake8 .  # Lint all Python files in the repo

    - name: Run unit tests with pytest
      run: |
        pytest gameunittest.py --maxfail=1 --disable-warnings -q  # Run tests in gameunittest.py
